language: node_js
node_js:
- stable
before_script:
- npm install -g mocha
- npm i
script:
- mocha
notifications:
  email: false
  slack:
    secure: rBREzv8oSTS0FURpRVfrXsiE7wTu8XZI36pj9x2BnmEJKU36Ua7dQy8XtGyiVjJWeE9ljEMP8rt2vFBJtxEDe5aaWMPZE8bFYDzZ5VVyh5l2Sj77vB4Yew7Q/vDZDo0YLuclJFiFyUKZwuLbMrrOikykcjwKYDqcvHhH0IxxFud0nO6YraSb1OEHrUxY0CdvDMup1FXltID1UAbbru21U8VFxflyFMROS3AfqVR7XhQ8/tygR5g2WPQIYjg1G9jKaJkLQz6aYp3Wmv33qK5m2ZFboTan8/WiitD6TVirNaBKimhyZ6pGO5p1vcYp/7hNccbeQJTlhSaEs+rGtJUk9lSB7ySyZpn5cJupwbdchJmp18n2vIbZHZhD7S0I7fDFovj/2KHas/JFOTg0dld4/05KSlDnypYCitRmyFSiJJYSMre9nwRNjIeT3XFOsF0WAXte2HOeLHrDoqlCUs527p7zTl7El7TErTTVB7Dlb5w1skSKqSNu4VzSrdArNYsBY6buag8Mo6zHd7SbvMgJJyM7sSJeiwwKhZRv57GvEyq593THKO7PiONYjBMKtSc3i6uPvqlnl8+6xWuJ63hIRbTGMaA5BBK3nh2s8j/EqinSOeksc0OFpOW6oUQtNI/j6+dxGrO+iRfxZHfgXvpwdS2xGDy5mDBji2OQ4qXkW00=
